# Generated by Django 4.2.29 on 2026-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vocabulary", "0002_userword_userword_unique_user_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название видео"),
                ),
                ("youtube_url", models.URLField(verbose_name="Ссылка на YouTube")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание видео"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начинающий"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, verbose_name="Только для Premium"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Длительность в секундах (опционально)",
                        null=True,
                        verbose_name="Длительность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True,
                        related_name="videos",
                        to="vocabulary.word",
                        verbose_name="Слова из видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
                "ordering": ["-created_at"],
            },
        ),
    ]
