# Generated by Django 4.2.29 on 2026-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="speaker",
            field=models.CharField(blank=True, max_length=200, verbose_name="Спикер"),
        ),
        migrations.AddField(
            model_name="video",
            name="topic",
            field=models.CharField(blank=True, max_length=200, verbose_name="Тема"),
        ),
    ]
