# Generated by Django 4.2.29 on 2026-04-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название темы"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание темы"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Термин (англ.)"
                    ),
                ),
                (
                    "transcription",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Транскрипция"
                    ),
                ),
                (
                    "translation_description",
                    models.TextField(verbose_name="Описание/перевод на русском"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="URL изображения"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, verbose_name="URL аудио (произношение)"
                    ),
                ),
                (
                    "example_sentence",
                    models.TextField(blank=True, verbose_name="Пример использования"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Легкий"), (2, "Средний"), (3, "Сложный")],
                        default=1,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="vocabulary.category",
                        verbose_name="Тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово",
                "verbose_name_plural": "Слова",
                "ordering": ["term"],
                "indexes": [
                    models.Index(fields=["term"], name="vocabulary__term_63816c_idx"),
                    models.Index(
                        fields=["category", "difficulty"],
                        name="vocabulary__categor_2a091c_idx",
                    ),
                ],
            },
        ),
    ]
