# Generated by Django 4.2.29 on 2026-04-11 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        default=0,
                        help_text="0=новое, 1=1день, 2=3дня, 3=7дней, 4=14дней, 5=30дней",
                        verbose_name="Этап повторения",
                    ),
                ),
                (
                    "next_review_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата следующего повторения",
                    ),
                ),
                (
                    "last_reviewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последнего повторения"
                    ),
                ),
                (
                    "times_reviewed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество повторений"
                    ),
                ),
                (
                    "is_deleted_by_user",
                    models.BooleanField(
                        default=False, verbose_name="Скрыто пользователем"
                    ),
                ),
                (
                    "is_learned",
                    models.BooleanField(
                        default=False, verbose_name="Полностью выучено"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_words",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_words",
                        to="vocabulary.word",
                        verbose_name="Слово",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово пользователя",
                "verbose_name_plural": "Слова пользователей",
                "ordering": ["next_review_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "next_review_date"],
                        name="vocabulary__user_id_412c5d_idx",
                    ),
                    models.Index(
                        fields=["user", "stage"], name="vocabulary__user_id_ef9ed7_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userword",
            constraint=models.UniqueConstraint(
                fields=("user", "word"), name="unique_user_word"
            ),
        ),
    ]
