# Generated by Django 4.2.29 on 2026-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0002_userword_userword_unique_user_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="userword",
            name="custom_description",
            field=models.TextField(blank=True, verbose_name="Описание/перевод"),
        ),
        migrations.AddField(
            model_name="userword",
            name="custom_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_words/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="userword",
            name="custom_term",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Свой термин"
            ),
        ),
        migrations.AddField(
            model_name="userword",
            name="custom_transcription",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Транскрипция"
            ),
        ),
    ]
