# Generated by Django 4.2.29 on 2026-04-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "vocabulary",
            "0003_userword_custom_description_userword_custom_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userword",
            name="word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_words",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
    ]
